# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: UiPathRunJob@4
  inputs:
    orchestratorConnection: 'UiPath Staging Connection'
    processName: 'Test.Git.Repot.and.Pipeline_Main.xaml'
    folderName: 'AzureDevOpsFolder'
    user: 'uipath\aziz.virani'
    machine: 'DESKTOP-8SI53PP'
